/**
 * Generate spec/requirements.yaml from the spec documents (REQ-ENG-002). Every unique REQ-*
 * (core) and REQ-APP-* (app) becomes one register row: id, excerpt, owning module(s), test
 * family, source spec. The CITED SECTION in the spec is canonical; excerpts are truncated.
 *
 * Provenance: this is generated by RUNNING this tool over the committed specs — never written
 * from memory. `pnpm reproduce` re-runs it and fails on drift.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

interface Req {
  id: string;
  excerpt: string;
  module: string;
  testFamily: string;
  spec: 'core' | 'app';
}

const ROOT = process.cwd();
const coreSpec = readFileSync(join(ROOT, 'spec/bsv-poker-spec.md'), 'utf8');
const appSpec = readFileSync(join(ROOT, 'spec/bsv-poker-app-architecture.md'), 'utf8');

/** Parse the core §19.F register table rows: | ID | excerpt | module(s) | test family |. */
function parseCoreTable(md: string): Map<string, Req> {
  const reqs = new Map<string, Req>();
  for (const line of md.split('\n')) {
    const m = /^\|\s*(REQ-[A-Z]+-\d+)\s*\|(.+?)\|(.+?)\|(.+?)\|\s*$/.exec(line);
    if (!m) continue;
    const id = m[1]!;
    reqs.set(id, {
      id,
      excerpt: m[2]!.trim(),
      module: m[3]!.trim(),
      testFamily: m[4]!.trim(),
      spec: 'core',
    });
  }
  return reqs;
}

/** Collect every unique REQ id in a document (catch any not in the table). */
function allIds(md: string, prefix: RegExp): string[] {
  const set = new Set<string>();
  for (const m of md.matchAll(prefix)) set.add(m[0]);
  return [...set].sort((a, b) => {
    const fa = a.replace(/\d+$/, '');
    const fb = b.replace(/\d+$/, '');
    if (fa !== fb) return fa < fb ? -1 : 1;
    return Number(a.match(/\d+$/)![0]) - Number(b.match(/\d+$/)![0]);
  });
}

/** Best-effort excerpt for an app REQ-APP-id: text on the line/paragraph where it is defined. */
function appExcerpt(md: string, id: string): string {
  // find "(REQ-APP-NNN" or "REQ-APP-NNN " followed by descriptive text
  const re = new RegExp(`${id}[):]?\\s+([^\\n]+)`);
  const m = re.exec(md);
  if (!m) return '(see app spec)';
  return m[1]!.replace(/\s+/g, ' ').slice(0, 140).trim();
}

function yamlEscape(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function main(): void {
  const core = parseCoreTable(coreSpec);
  // ensure every core id present even if not in the table
  for (const id of allIds(coreSpec, /REQ-(?!APP)[A-Z]+-\d+/g)) {
    if (!core.has(id)) {
      core.set(id, { id, excerpt: '(see cited section)', module: '(tbd)', testFamily: '(tbd)', spec: 'core' });
    }
  }
  const appReqs: Req[] = allIds(appSpec, /REQ-APP-\d+/g).map((id) => ({
    id,
    excerpt: appExcerpt(appSpec, id),
    module: '(app layer — see §A18)',
    testFamily: '(see §A16)',
    spec: 'app',
  }));

  const all: Req[] = [...core.values(), ...appReqs];
  const lines: string[] = [
    '# Requirements register — generated by tools/extract-requirements.ts (REQ-ENG-002).',
    '# The cited spec section is canonical; excerpts are truncated. Do not edit by hand.',
    `# counts: core=${core.size} app=${appReqs.length} total=${all.length}`,
    'requirements:',
  ];
  for (const r of all) {
    lines.push(`  - id: ${r.id}`);
    lines.push(`    spec: ${r.spec}`);
    lines.push(`    excerpt: ${yamlEscape(r.excerpt)}`);
    lines.push(`    module: ${yamlEscape(r.module)}`);
    lines.push(`    testFamily: ${yamlEscape(r.testFamily)}`);
  }
  mkdirSync(join(ROOT, 'spec'), { recursive: true });
  const out = lines.join('\n') + '\n';
  writeFileSync(join(ROOT, 'spec/requirements.yaml'), out);
  console.log(`requirements.yaml written: core=${core.size} app=${appReqs.length} total=${all.length}`);
}

main();
