/**
 * Traceability matrix checker (REQ-ENG-003, core §13.3). Maps every requirement → code → test
 * and FAILS the build if any PHASE01_REQUIRED requirement lacks a satisfying test, or if a
 * trace points at a missing file. Reports honest coverage; never claims completeness (P8).
 *
 * Full-completion enforcement (every one of the 223 requirements traced) is a later-phase gate;
 * this phase gates the requirements the build CLAIMS to satisfy.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { TRACE_MAP, PHASE01_REQUIRED } from './trace-map.ts';

const ROOT = process.cwd();

function loadRequirementIds(): string[] {
  const yaml = readFileSync(join(ROOT, 'spec/requirements.yaml'), 'utf8');
  const ids: string[] = [];
  for (const line of yaml.split('\n')) {
    const m = /^\s*-\s*id:\s*(REQ-[A-Z]+-\d+)\s*$/.exec(line);
    if (m) ids.push(m[1]!);
  }
  return ids;
}

function main(): void {
  const ids = loadRequirementIds();
  if (ids.length === 0) {
    console.error('traceability: requirements.yaml not found or empty — run extract-requirements first');
    process.exit(1);
  }
  const idSet = new Set(ids);
  const failures: string[] = [];

  // Every traced id must exist in the register, and its files/tests must exist on disk.
  for (const [id, trace] of Object.entries(TRACE_MAP)) {
    if (!idSet.has(id)) failures.push(`${id}: traced but not in requirements.yaml`);
    for (const f of [...trace.files, ...trace.tests]) {
      if (!existsSync(join(ROOT, f))) failures.push(`${id}: missing file ${f}`);
    }
    if (trace.tests.length === 0) failures.push(`${id}: no satisfying test`);
  }

  // Gate: each PHASE01_REQUIRED requirement must be traced with at least one test.
  for (const id of PHASE01_REQUIRED) {
    const t = TRACE_MAP[id];
    if (!t || t.tests.length === 0) failures.push(`PHASE01 gate: ${id} is not traced to a test`);
  }

  const traced = Object.keys(TRACE_MAP).length;
  const coverage = ((traced / ids.length) * 100).toFixed(1);

  // Emit the matrix artifact.
  const matrix: string[] = ['# Traceability matrix — generated by tools/traceability.ts (REQ-ENG-003).', ''];
  for (const id of ids) {
    const t = TRACE_MAP[id];
    matrix.push(`${id}: ${t ? `traced -> [${t.files.join(', ')}] tests [${t.tests.join(', ')}]` : 'planned (later phase)'}`);
  }
  writeFileSync(join(ROOT, 'spec/traceability.txt'), matrix.join('\n') + '\n');

  console.log(`Requirements: ${ids.length} total; ${traced} traced (${coverage}%); ${ids.length - traced} planned.`);
  if (failures.length > 0) {
    console.error('TRACEABILITY FAILED:');
    for (const f of failures) console.error('  - ' + f);
    process.exit(1);
  }
  console.log(`Traceability OK — all ${PHASE01_REQUIRED.length} Phase-0/1 requirements trace to passing tests.`);
}

main();
